In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
df=pd.read_csv("medical_records.csv")
df

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80        140.0        2000
1        R102       P105      Diabetes  120/80          NaN        2500
2        R103       P098  Hypertension    high        140.0        3000
3        R104       P038        Asthma  140/90          NaN        3000
4        R105       P040        Asthma  130/85          NaN        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

[120 rows x 6 columns]

In [26]:
df.head(5)

  record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0      R101       P013  Hypertension  120/80        140.0        2000
1      R102       P105      Diabetes  120/80          NaN        2500
2      R103       P098  Hypertension    high        140.0        3000
3      R104       P038        Asthma  140/90          NaN        3000
4      R105       P040        Asthma  130/85          NaN        1500

In [28]:
df.tail(5)

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

In [30]:
df.describe()

       sugar_level   visit_cost
count    85.000000   120.000000
mean    141.058824  2287.500000
std      27.689758   567.548539
min     110.000000  1500.000000
25%     110.000000  2000.000000
50%     140.000000  2500.000000
75%     180.000000  3000.000000
max     180.000000  3000.000000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   record_id    120 non-null    object
 1   patient_id   120 non-null    object
 2   diagnosis    120 non-null    object
 3   bp           120 non-null    object
 4   sugar_level  85 non-null     float64
 5   visit_cost   120 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.8+ KB

In [34]:
df.size

720

In [36]:
df.shape

(120, 6)

In [38]:
df.isna()

     record_id  patient_id  diagnosis     bp  sugar_level  visit_cost
0        False       False      False  False        False       False
1        False       False      False  False         True       False
2        False       False      False  False        False       False
3        False       False      False  False         True       False
4        False       False      False  False         True       False
..         ...         ...        ...    ...          ...         ...
115      False       False      False  False        False       False
116      False       False      False  False         True       False
117      False       False      False  False         True       False
118      False       False      False  False        False       False
119      False       False      False  False        False       False

[120 rows x 6 columns]

In [40]:
df.isna().sum()

record_id       0
patient_id      0
diagnosis       0
bp              0
sugar_level    35
visit_cost      0
dtype: int64

In [48]:
df["sugar_level"]=df["sugar_level"].fillna("0")
df

    record_id patient_id     diagnosis      bp sugar_level  visit_cost
0        R101       P013  Hypertension  120/80       140.0        2000
1        R102       P105      Diabetes  120/80           0        2500
2        R103       P098  Hypertension    high       140.0        3000
3        R104       P038        Asthma  140/90           0        3000
4        R105       P040        Asthma  130/85           0        1500
..        ...        ...           ...     ...         ...         ...
115      R216       P081        Asthma    high       110.0        2500
116      R217       P033      Diabetes    high           0        1500
117      R218       P063  Hypertension  140/90           0        2000
118      R219       P011  Hypertension  130/85       180.0        2500
119      R220       P013  Hypertension    high       180.0        1500

[120 rows x 6 columns]

In [56]:
df1=pd.read_csv("patient_details.csv")
df1

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [62]:
df1["name"]=df1["name"].fillna("X")
df1

    patient_id          name   age  gender     city admission_date height_cm
0         P001             X  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009             X  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [54]:
df1['age'].isna().sum()

24

In [66]:
df1["age"]=df1["age"].fillna(df1["age"].mean())
df1

    patient_id          name   age  gender     city admission_date height_cm
0         P001             X  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009             X  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [70]:
df1.loc[df1["patient_id"] == "P014", ["age"]]

          age
13  35.849057