In [13]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [19]:
df = pd.read_csv("patient_details.csv")
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [21]:
print(df.isnull().sum())

patient_id         0
name              23
age               24
gender             0
city               0
admission_date     0
height_cm          0
dtype: int64

In [25]:
df['name'].fillna("Unknown", inplace=True)
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001       Unknown  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009       Unknown  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [75]:
df['age'].fillna(df['age'].mean(), inplace=True)


df

C:\Users\Diskha Rawat\AppData\Local\Temp\ipykernel_17472\4000482651.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [59]:
df['height_cm'] = pd.to_numeric(df['height_cm'], errors='coerce')# errors='coerce' means If Python finds a value that cannot be converted into a number, it will replace it with NaN (missing value).
df

,patient_id,name,age,gender,city,admission_date,height_cm
0,P001,Unknown,25.000000,F,Mumbai,2024-01-15,180.0
1,P002,Rahul Sharma,60.000000,F,Delhi,2024-01-16,170.0
2,P003,Neha Singh,45.000000,M,Mumbai,2024-01-16,150.0
3,P004,Neha Singh,60.000000,M,Kolkata,2024-01-15,170.0
4,P005,Neha Singh,25.000000,M,Kolkata,2024-01-15,180.0
...,...,...,...,...,...,...,...
115,P116,John Paul,30.000000,F,Mumbai,2024-01-15,NaN
116,P117,Anita Verma,45.000000,M,Delhi,2024-01-15,170.0
117,P118,Unknown,60.000000,F,Delhi,2024-01-15,NaN
118,P119,John Paul,35.849057,M,Mumbai,2024-01-16,160.0
119,P120,Neha Singh,35.849057,M,Kolkata,2024-01-15,170.0

In [73]:
df['height_cm'].fillna(df['height_cm'].mean(), inplace=True)
df['height_cm'] = df['height_cm'].astype(int)
df

,patient_id,name,age,gender,city,admission_date,height_cm
0,P001,Unknown,25.000000,F,Mumbai,2024-01-15,180
1,P002,Rahul Sharma,60.000000,F,Delhi,2024-01-16,170
2,P003,Neha Singh,45.000000,M,Mumbai,2024-01-16,150
3,P004,Neha Singh,60.000000,M,Kolkata,2024-01-15,170
4,P005,Neha Singh,25.000000,M,Kolkata,2024-01-15,180
...,...,...,...,...,...,...,...
115,P116,John Paul,30.000000,F,Mumbai,2024-01-15,165
116,P117,Anita Verma,45.000000,M,Delhi,2024-01-15,170
117,P118,Unknown,60.000000,F,Delhi,2024-01-15,165
118,P119,John Paul,35.849057,M,Mumbai,2024-01-16,160
119,P120,Neha Singh,35.849057,M,Kolkata,2024-01-15,170

In [77]:
df['gender'] = df['gender'].str.upper()

df['gender'] = df['gender'].replace({
    "MALE":"M",
    "FEMALE":"F"
})
df

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [79]:
df['city'] = df['city'].str.title()
df

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [81]:
df['admission_date'] = pd.to_datetime(df['admission_date'], format='mixed', dayfirst=True)
df

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [83]:
df.drop_duplicates(inplace=True)
df

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [85]:
df.reset_index(drop=True, inplace=True)
df

    patient_id          name  age gender     city admission_date  height_cm
0         P001       Unknown   25      F   Mumbai     2024-01-15        180
1         P002  Rahul Sharma   60      F    Delhi     2024-01-16        170
2         P003    Neha Singh   45      M   Mumbai     2024-01-16        150
3         P004    Neha Singh   60      M  Kolkata     2024-01-15        170
4         P005    Neha Singh   25      M  Kolkata     2024-01-15        180
..         ...           ...  ...    ...      ...            ...        ...
115       P116     John Paul   30      F   Mumbai     2024-01-15        165
116       P117   Anita Verma   45      M    Delhi     2024-01-15        170
117       P118       Unknown   60      F    Delhi     2024-01-15        165
118       P119     John Paul   35      M   Mumbai     2024-01-16        160
119       P120    Neha Singh   35      M  Kolkata     2024-01-15        170

[120 rows x 7 columns]

In [93]:
# normalization
mm = MinMaxScaler()
scaled_data = pd.DataFrame(mm.fit_transform(df[['age','height_cm']]))
print(scaled_data)

            0         1
0    0.461538  1.000000
1    1.000000  0.666667
2    0.769231  0.000000
3    1.000000  0.666667
4    0.461538  1.000000
..        ...       ...
115  0.538462  0.500000
116  0.769231  0.666667
117  1.000000  0.500000
118  0.615385  0.333333
119  0.615385  0.666667

[120 rows x 2 columns]

In [97]:
# standardization
ss = StandardScaler()
scaled_data = pd.DataFrame(ss.fit_transform(df[['age','height_cm']]))
print(scaled_data)

            0         1
0   -0.530523  1.548641
1    1.310962  0.480613
2    0.521754 -1.655444
3    1.310962  0.480613
4   -0.530523  1.548641
..        ...       ...
115 -0.267454 -0.053401
116  0.521754  0.480613
117  1.310962 -0.053401
118 -0.004384 -0.587416
119 -0.004384  0.480613

[120 rows x 2 columns]

In [99]:
scaled_data.mean(),scaled_data.std()

(0   -1.461794e-16
 1    2.590520e-17
 dtype: float64,
 0    1.004193
 1    1.004193
 dtype: float64)

In [101]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.preprocessing import LabelEncoder

In [105]:
gender = pd.get_dummies(df['gender'], dtype = int)
gender

     F  M
0    1  0
1    1  0
2    0  1
3    0  1
4    0  1
..  .. ..
115  1  0
116  0  1
117  1  0
118  0  1
119  0  1

[120 rows x 2 columns]